MyWidget:

<MyWidget>:
    BoxLayout:
    # cols: 1
        # orientation: "vertical"
        # orientation: "horinzontal"
        # size: root.width, root.height
        padding: 50
        spacing: 20
        Image:
            source: r"C:\Users\flpas\OneDrive\Programing\Kivy\resources_kivy\RESOURCES_KIVY\1_THE_LAB\RESOURCES\images\cake.jpg"
            # source: "resources_kivy\RESOURCES_KIVY\1_THE_LAB\RESOURCES\images\cake.jpg"
            allow_stretch: True
            # keep_aspect_ratio: true
        # Label:
            # color: 
            # text: "Hello"
