# MainWidget:

    # BoxLayout:

    #     orientation: "vertical"
    #     size: root.width, root.height
        # BoxLayout:
        #     Button:
        #         text: "ZZZ"

        # BoxLayout:
            # Color: (1,1,1,1)
            # cols: 3
            # Button:
            #     text: "A"
            # Button:
                # text: "B"
        # Image:
        #     source: r"C:\Users\flpas\OneDrive\Flpasana\Identifications\ID's\ProfilePic.jpg"
            # allow_stretch: True
                # pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                    # size_hint: 1, 1
            # Button:
            #     text: "C"