# :kivy 2.1.0
<MyRoot>:

    random_label: random_label
    BoxLayout:
        orientation: "vertical"
        Label:
            text: "Number"
            font_size: 64
            color: .92, .45, 0, 1

        Label:
            id: random_label
            text: "-"
            font_size: 64
        Button:
            text: "Generate"
            font_size: 32
            size: 100, 50
            on_press: root.Generate_number()